/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpeakingFreeRouteImport } from './routes/_authenticated/speaking-free'
import { Route as AuthenticatedSpeakingRouteImport } from './routes/_authenticated/speaking'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedPlacementRouteImport } from './routes/_authenticated/placement'
import { Route as AuthenticatedListeningRouteImport } from './routes/_authenticated/listening'
import { Route as AuthenticatedExerciseRouteImport } from './routes/_authenticated/exercise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpeakingFreeRoute =
  AuthenticatedSpeakingFreeRouteImport.update({
    id: '/speaking-free',
    path: '/speaking-free',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpeakingRoute = AuthenticatedSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementRoute = AuthenticatedPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListeningRoute = AuthenticatedListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciseRoute = AuthenticatedExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercise': typeof AuthenticatedExerciseRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/placement': typeof AuthenticatedPlacementRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
  '/speaking-free': typeof AuthenticatedSpeakingFreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercise': typeof AuthenticatedExerciseRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/placement': typeof AuthenticatedPlacementRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
  '/speaking-free': typeof AuthenticatedSpeakingFreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercise': typeof AuthenticatedExerciseRoute
  '/_authenticated/listening': typeof AuthenticatedListeningRoute
  '/_authenticated/placement': typeof AuthenticatedPlacementRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/speaking': typeof AuthenticatedSpeakingRoute
  '/_authenticated/speaking-free': typeof AuthenticatedSpeakingFreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/exercise'
    | '/listening'
    | '/placement'
    | '/progress'
    | '/speaking'
    | '/speaking-free'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/exercise'
    | '/listening'
    | '/placement'
    | '/progress'
    | '/speaking'
    | '/speaking-free'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercise'
    | '/_authenticated/listening'
    | '/_authenticated/placement'
    | '/_authenticated/progress'
    | '/_authenticated/speaking'
    | '/_authenticated/speaking-free'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/speaking-free': {
      id: '/_authenticated/speaking-free'
      path: '/speaking-free'
      fullPath: '/speaking-free'
      preLoaderRoute: typeof AuthenticatedSpeakingFreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speaking': {
      id: '/_authenticated/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof AuthenticatedSpeakingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement': {
      id: '/_authenticated/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof AuthenticatedPlacementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listening': {
      id: '/_authenticated/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthenticatedListeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise': {
      id: '/_authenticated/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof AuthenticatedExerciseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExerciseRoute: typeof AuthenticatedExerciseRoute
  AuthenticatedListeningRoute: typeof AuthenticatedListeningRoute
  AuthenticatedPlacementRoute: typeof AuthenticatedPlacementRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSpeakingRoute: typeof AuthenticatedSpeakingRoute
  AuthenticatedSpeakingFreeRoute: typeof AuthenticatedSpeakingFreeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExerciseRoute: AuthenticatedExerciseRoute,
  AuthenticatedListeningRoute: AuthenticatedListeningRoute,
  AuthenticatedPlacementRoute: AuthenticatedPlacementRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSpeakingRoute: AuthenticatedSpeakingRoute,
  AuthenticatedSpeakingFreeRoute: AuthenticatedSpeakingFreeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
